# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crown_generate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CrownGenerate(object):
    def setupUi(self, CrownGenerate):
        CrownGenerate.setObjectName("CrownGenerate")
        CrownGenerate.setWindowModality(QtCore.Qt.WindowModal)
        CrownGenerate.resize(702, 522)
        font = QtGui.QFont()
        font.setPointSize(18)
        CrownGenerate.setFont(font)
        self.centralwidget = QtWidgets.QWidget(CrownGenerate)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, -10, 841, 701))
        self.listView.setStyleSheet("background-image: url(:/crown_generate/13.jpeg);\n"
                                    "")
        self.listView.setObjectName("listView")
        self.welcome = QtWidgets.QLabel(self.centralwidget)
        self.welcome.setGeometry(QtCore.QRect(20, 10, 431, 51))
        self.welcome.setStyleSheet("font-family:\"Microsoft Yahei\";\n"
                                   "font-size: 28pt;\n"
                                   "color: rgba(255, 0, 0, 0.5); \n"
                                   "font-weight: bold; \n"
                                   "font-style: italic;\n"
                                   "\n"
                                   "\n"
                                   "")
        self.welcome.setObjectName("welcome")
        self.toothNumber = QtWidgets.QLabel(self.centralwidget)
        self.toothNumber.setGeometry(QtCore.QRect(60, 150, 221, 51))
        font = QtGui.QFont()
        font.setFamily("迷你简粗仿宋")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.toothNumber.setFont(font)
        self.toothNumber.setStyleSheet("color: blue;\n"
                                       "background-image: url(:/crown_generate/16.jpg);\n"
                                       "background-color: rgb(143, 143, 213);\n"
                                       "font:22pt \"迷你简粗仿宋\";\n"
                                       "background-color: rgba(255, 255, 255, 0.2);\n"
                                       "width:150px;\n"
                                       "border: 2px inset grey; padding: 10px;\n"
                                       "\n"
                                       "")
        self.toothNumber.setObjectName("toothNumber")
        self.generateModel = QtWidgets.QLabel(self.centralwidget)
        self.generateModel.setGeometry(QtCore.QRect(370, 140, 231, 61))
        font = QtGui.QFont()
        font.setFamily("迷你简粗仿宋")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.generateModel.setFont(font)
        self.generateModel.setStyleSheet("color: blue;\n"
                                         "background-image: url(:/crown_generate/17.jpg);\n"
                                         "background-color: rgb(143, 143, 213);\n"
                                         "font:22pt \"迷你简粗仿宋\";\n"
                                         "background-color: rgba(255, 255, 255, 100);\n"
                                         "width:150px;\n"
                                         "border: 2px inset grey; padding: 10px;\n"
                                         "")
        self.generateModel.setObjectName("generateModel")
        self.btn_upper = QtWidgets.QPushButton(self.centralwidget)
        self.btn_upper.setGeometry(QtCore.QRect(400, 230, 171, 50))
        self.btn_upper.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setItalic(True)
        self.btn_upper.setFont(font)
        self.btn_upper.setStyleSheet("\n"
                                     "background-image: url(:/crown_generate/img2.jpeg);")
        self.btn_upper.setObjectName("btn_upper")
        self.btn_lower = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lower.setGeometry(QtCore.QRect(400, 300, 171, 50))
        self.btn_lower.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setItalic(True)
        self.btn_lower.setFont(font)
        self.btn_lower.setStyleSheet("\n"
                                     "background-image: url(:/crown_generate/img2.jpeg);")
        self.btn_lower.setObjectName("btn_lower")
        self.tooth_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.tooth_7.setGeometry(QtCore.QRect(190, 300, 100, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tooth_7.sizePolicy().hasHeightForWidth())
        self.tooth_7.setSizePolicy(sizePolicy)
        self.tooth_7.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setItalic(True)
        self.tooth_7.setFont(font)
        self.tooth_7.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
                                   "background-image: url(:/crown_generate/15.jpg);\n"
                                   "width:150px;\n"
                                   "border: 2px inset grey; padding: 10px;\n"
                                   "")
        self.tooth_7.setObjectName("tooth_7")
        self.tooth_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.tooth_6.setGeometry(QtCore.QRect(190, 230, 100, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tooth_6.sizePolicy().hasHeightForWidth())
        self.tooth_6.setSizePolicy(sizePolicy)
        self.tooth_6.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setItalic(True)
        self.tooth_6.setFont(font)
        self.tooth_6.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
                                   "background-image: url(:/crown_generate/15.jpg);\n"
                                   "width:150px;\n"
                                   "border: 2px inset grey; padding: 10px;\n"
                                   "")
        self.tooth_6.setObjectName("tooth_6")
        self.tooth_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.tooth_5.setGeometry(QtCore.QRect(60, 300, 100, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tooth_5.sizePolicy().hasHeightForWidth())
        self.tooth_5.setSizePolicy(sizePolicy)
        self.tooth_5.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setItalic(True)
        self.tooth_5.setFont(font)
        self.tooth_5.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
                                   "background-image: url(:/crown_generate/15.jpg);\n"
                                   "width:150px;\n"
                                   "border: 2px inset grey; padding: 10px;\n"
                                   "\n"
                                   "")
        self.tooth_5.setObjectName("tooth_5")
        self.tooth_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.tooth_4.setGeometry(QtCore.QRect(60, 230, 100, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tooth_4.sizePolicy().hasHeightForWidth())
        self.tooth_4.setSizePolicy(sizePolicy)
        self.tooth_4.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setItalic(True)
        font.setUnderline(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tooth_4.setFont(font)
        self.tooth_4.setTabletTracking(False)
        self.tooth_4.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
                                   "background-image: url(:/crown_generate/15.jpg);\n"
                                   "width:100px;\n"
                                   "border: 2px inset grey; padding: 10px;\n"
                                   "\n"
                                   "")
        self.tooth_4.setObjectName("tooth_4")
        CrownGenerate.setCentralWidget(self.centralwidget)

        self.retranslateUi(CrownGenerate)
        self.btn_upper.clicked.connect(CrownGenerate.btn_upper_click)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CrownGenerate)

    def retranslateUi(self, CrownGenerate):
        _translate = QtCore.QCoreApplication.translate
        CrownGenerate.setWindowTitle(_translate("CrownGenerate", "CrownGenerate"))
        self.welcome.setText(_translate("CrownGenerate", "欢迎来到牙齿生成界面"))
        self.toothNumber.setText(_translate("CrownGenerate", "请选择牙位号："))
        self.generateModel.setText(_translate("CrownGenerate", "请选择生成模型："))
        self.btn_upper.setText(_translate("CrownGenerate", "upper"))
        self.btn_lower.setText(_translate("CrownGenerate", "lower"))
        self.tooth_7.setText(_translate("CrownGenerate", "7"))
        self.tooth_6.setText(_translate("CrownGenerate", "6"))
        self.tooth_5.setText(_translate("CrownGenerate", "5"))
        self.tooth_4.setText(_translate("CrownGenerate", "4"))
